import { Pane } from 'tweakpane';

interface FileTypeStats {
  fileType: string;
  count: number;
  totalLines: number;
  totalWords: number;
}

interface ProjectStatistics {
  timestamp: string;
  fileTypes: FileTypeStats[];
  totals: {
    files: number;
    lines: number;
    words: number;
  };
}

class StatisticsViewer {
  private pane!: Pane;
  private selectedFile: string = '';
  private availableFiles: string[] = [];
  private statisticsPanel: HTMLElement;

  constructor() {
    this.statisticsPanel = document.getElementById('statistics-panel')!;
    this.init();
  }

  private async init() {
    await this.loadAvailableFiles();
    this.initTweakpane();
  }

  private async loadAvailableFiles() {
    // Try to load an index file first (generated by the statistics script)
    try {
      const indexResponse = await fetch('/src/assets/project-statistics/index.json');
      if (indexResponse.ok) {
        const index = await indexResponse.json();
        this.availableFiles = index.files || [];
      }
    } catch (error) {
      // Index file doesn't exist, try fallback discovery
      console.log('No index file found, trying to discover files...');
      
      // Fallback: try to discover files by attempting to fetch them
      // This is less efficient but works if index.json hasn't been generated yet
      const now = new Date();
      const year = now.getFullYear();
      const month = String(now.getMonth() + 1).padStart(2, '0');
      const day = String(now.getDate()).padStart(2, '0');
      
      // Try files from today (check common time intervals)
      const hoursToTry = Array.from({ length: 24 }, (_, i) => String(i).padStart(2, '0'));
      const minutesToTry = ['00', '05', '10', '15', '20', '25', '30', '35', '40', '45', '50', '55'];
      
      const filesToTry: string[] = [];
      for (const hour of hoursToTry) {
        for (const minute of minutesToTry) {
          filesToTry.push(`${year}-${month}-${day}_${hour}-${minute}.json`);
        }
      }

      // Test which files exist (limit concurrent requests)
      const batchSize = 20;
      for (let i = 0; i < filesToTry.length; i += batchSize) {
        const batch = filesToTry.slice(i, i + batchSize);
        const results = await Promise.allSettled(
          batch.map(file => fetch(`/src/assets/project-statistics/${file}`))
        );
        
        results.forEach((result, idx) => {
          if (result.status === 'fulfilled' && result.value.ok) {
            this.availableFiles.push(batch[idx]);
          }
        });
      }
    }

    // Files are already sorted by the index (newest first)
    // But ensure they're sorted if we used fallback
    if (this.availableFiles.length > 0 && !this.availableFiles[0].includes('index.json')) {
      this.availableFiles.sort().reverse();
    }

    if (this.availableFiles.length > 0) {
      this.selectedFile = this.availableFiles[0];
    }
  }

  private initTweakpane() {
    const container = document.getElementById('tweakpane-container');
    if (!container) return;

    this.pane = new Pane({ 
      title: 'Statistics Files',
      container: container
    });

    const config = {
      selectedFile: this.selectedFile,
    };

    // Create options object for dropdown
    const options: Record<string, string> = {};
    this.availableFiles.forEach(file => {
      // Use filename as both key and value, but display a nicer format
      const displayName = file.replace('.json', '').replace(/_/g, ' ').replace(/-/g, '/');
      options[displayName] = file;
    });

    this.pane.addBinding(config, 'selectedFile', {
      options: options,
      label: 'Statistics File',
    }).on('change', (ev) => {
      this.selectedFile = ev.value;
      this.loadStatistics(this.selectedFile);
    });

    // Load initial file
    if (this.selectedFile) {
      this.loadStatistics(this.selectedFile);
    }
  }

  private async loadStatistics(filename: string) {
    try {
      const response = await fetch(`/src/assets/project-statistics/${filename}`);
      if (!response.ok) {
        throw new Error(`Failed to load ${filename}`);
      }

      const data: ProjectStatistics = await response.json();
      this.displayStatistics(data);
    } catch (error) {
      console.error('Error loading statistics:', error);
      this.statisticsPanel.innerHTML = `
        <div class="no-data">
          <p>Error loading statistics file: ${filename}</p>
          <p>${error instanceof Error ? error.message : 'Unknown error'}</p>
        </div>
      `;
    }
  }

  private displayStatistics(data: ProjectStatistics) {
    const timestamp = new Date(data.timestamp).toLocaleString();
    
    this.statisticsPanel.innerHTML = `
      <h2>Project Statistics</h2>
      
      <div class="stat-section">
        <h3>Overview</h3>
        <div class="stat-grid">
          <div class="stat-item">
            <div class="stat-item-label">Total Files</div>
            <div class="stat-item-value">${data.totals.files.toLocaleString()}</div>
          </div>
          <div class="stat-item">
            <div class="stat-item-label">Total Lines</div>
            <div class="stat-item-value">${data.totals.lines.toLocaleString()}</div>
          </div>
          <div class="stat-item">
            <div class="stat-item-label">Total Words</div>
            <div class="stat-item-value">${data.totals.words.toLocaleString()}</div>
          </div>
          <div class="stat-item">
            <div class="stat-item-label">Generated</div>
            <div class="stat-item-value" style="font-size: 14px;">${timestamp}</div>
          </div>
        </div>
      </div>

      <div class="stat-section">
        <h3>File Types Breakdown</h3>
        <table class="file-type-table">
          <thead>
            <tr>
              <th>File Type</th>
              <th>Count</th>
              <th>Lines</th>
              <th>Words</th>
            </tr>
          </thead>
          <tbody>
            ${data.fileTypes.map(ft => `
              <tr>
                <td class="file-type">${ft.fileType || '(no extension)'}</td>
                <td>${ft.count.toLocaleString()}</td>
                <td>${ft.totalLines.toLocaleString()}</td>
                <td>${ft.totalWords.toLocaleString()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    `;
  }
}

// Initialize the statistics viewer when the page loads
new StatisticsViewer();

